name: binary_interop
version: 0.0.20
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Binary interop is a library that allows load shared libraries, invoke their functions and get access to their data.
homepage: https://github.com/mezoni/binary_interop
dependencies:
  binary_declarations:
    git: https://github.com/mezoni/binary_declarations
  binary_types:
    git: https://github.com/mezoni/binary_types
  file_utils: any
  libffi_binaries: any
  path: any
  pub_semver: any
  system_info: any
  unsafe_extension: any
dev_dependencies:
  unittest: any
